# Generated by Django 6.0 on 2026-03-06 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora programada para la cita', verbose_name='Fecha y Hora')),
                ('duracion_estimada', models.PositiveIntegerField(default=60, help_text='Duración estimada del servicio en minutos', verbose_name='Duración Estimada (minutos)')),
                ('tipo_servicio', models.CharField(choices=[('MANT', 'Mantenimiento General'), ('ACEI', 'Cambio de Aceite'), ('REVI', 'Revisión'), ('REPA', 'Reparación'), ('ITV', 'Inspección Técnica (ITV)'), ('NEUM', 'Neumáticos'), ('FREN', 'Frenos'), ('SUSP', 'Suspensión'), ('ELEC', 'Sistema Eléctrico'), ('MOTO', 'Motor'), ('DIAG', 'Diagnóstico'), ('OTRO', 'Otro')], max_length=4, verbose_name='Tipo de Servicio')),
                ('descripcion', models.TextField(help_text='Descripción del servicio solicitado', verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('CONF', 'Confirmada'), ('PROC', 'En Proceso'), ('COMP', 'Completada'), ('CANC', 'Cancelada'), ('NOASIS', 'No Asistió')], default='PEND', max_length=6, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales para el taller', verbose_name='Notas Internas')),
                ('recordatorio_enviado', models.BooleanField(default=False, help_text='Indica si se envió recordatorio al cliente', verbose_name='Recordatorio Enviado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cliente', models.ForeignKey(help_text='Cliente que solicita el servicio', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clientes.cliente', verbose_name='Cliente')),
                ('mecanico_asignado', models.ForeignKey(blank=True, help_text='Mecánico responsable del servicio', limit_choices_to={'activo': True, 'rol': 'MECANICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Mecánico Asignado')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('vehiculo', models.ForeignKey(help_text='Vehículo a atender', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora', 'estado'], name='citas_cita_fecha_h_e91b0d_idx'), models.Index(fields=['mecanico_asignado', 'fecha_hora'], name='citas_cita_mecanic_c96778_idx'), models.Index(fields=['cliente'], name='citas_cita_cliente_a6c6b6_idx'), models.Index(fields=['vehiculo'], name='citas_cita_vehicul_3a6bac_idx')],
            },
        ),
    ]
