# Generated by Django 6.0 on 2026-03-06 12:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, help_text='Número único de la orden de trabajo', max_length=20, unique=True, verbose_name='Número de Orden')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('estado', models.CharField(choices=[('ABIE', 'Abierta'), ('PROC', 'En Proceso'), ('PAUS', 'Pausada'), ('COMP', 'Completada'), ('CANC', 'Cancelada')], default='ABIE', max_length=4, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORM', 'Normal'), ('ALTA', 'Alta'), ('URGE', 'Urgente')], default='NORM', max_length=4, verbose_name='Prioridad')),
                ('kilometros_ingreso', models.PositiveIntegerField(help_text='Kilometraje del vehículo al ingresar al taller', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Kilómetros al Ingreso')),
                ('descripcion_problema', models.TextField(help_text='Descripción del problema reportado por el cliente', verbose_name='Descripción del Problema')),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico técnico realizado por el mecánico', verbose_name='Diagnóstico')),
                ('trabajos_realizados', models.TextField(blank=True, help_text='Descripción detallada de los trabajos realizados', verbose_name='Trabajos Realizados')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la orden', verbose_name='Observaciones')),
                ('tiempo_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo estimado de trabajo en horas', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tiempo Estimado (horas)')),
                ('tiempo_real', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo real de trabajo en horas', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tiempo Real (horas)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cita', models.ForeignKey(blank=True, help_text='Cita que originó esta orden (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='citas.cita', verbose_name='Cita Asociada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.cliente', verbose_name='Cliente')),
                ('mecanico_asignado', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'rol': 'MECANICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Mecánico Asignado')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='LineaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del Trabajo')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Horas')),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por Hora (€)')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_trabajo', to='ordenes.ordentrabajo', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Línea de Trabajo',
                'verbose_name_plural': 'Líneas de Trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LineaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del Repuesto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario (€)')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento en porcentaje (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Descuento (%)')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_repuesto', to='ordenes.ordentrabajo', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Línea de Repuesto',
                'verbose_name_plural': 'Líneas de Repuesto',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['numero_orden'], name='ordenes_ord_numero__e0412a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado', 'fecha_apertura'], name='ordenes_ord_estado_bb2855_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['mecanico_asignado', 'estado'], name='ordenes_ord_mecanic_607fed_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['cliente'], name='ordenes_ord_cliente_67c6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['vehiculo'], name='ordenes_ord_vehicul_3846d1_idx'),
        ),
    ]
