# Generated by Django 6.0 on 2026-03-05 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('dni', models.CharField(help_text='Formato: 12345678A o X1234567A', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de DNI/NIE inválido. Debe ser 12345678A o X1234567A', regex='^[0-9]{8}[A-Z]$|^[XYZ][0-9]{7}[A-Z]$')], verbose_name='DNI/NIE')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(help_text='Formato: +34600000000', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido. Ej: +34600000000 o 600000000', regex='^\\+?[0-9]{9,15}$')], verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, help_text='Opcional', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido. Ej: +34600000000 o 600000000', regex='^\\+?[0-9]{9,15}$')], verbose_name='Teléfono alternativo')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe tener 5 dígitos', regex='^[0-9]{5}$')], verbose_name='Código postal')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre el cliente', verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, help_text='Los clientes inactivos no aparecen en búsquedas', verbose_name='Cliente activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
                'permissions': [('ver_clientes_inactivos', 'Puede ver clientes inactivos')],
                'indexes': [models.Index(fields=['dni'], name='clientes_cl_dni_5e5da9_idx'), models.Index(fields=['apellidos', 'nombre'], name='clientes_cl_apellid_fb9e6a_idx'), models.Index(fields=['-fecha_registro'], name='clientes_cl_fecha_r_483ee3_idx')],
            },
        ),
    ]
