# Generated by Django 6.0 on 2026-03-06 13:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(help_text='Código único de la categoría', max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Repuesto',
                'verbose_name_plural': 'Categorías de Repuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del repuesto', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('ubicacion_almacen', models.CharField(blank=True, help_text='Ejemplo: Estante A3, Pasillo 2, etc.', max_length=50, verbose_name='Ubicación en Almacén')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Nivel mínimo para generar alerta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Máximo')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Compra (€)')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Venta (€)')),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Porcentaje de IVA aplicable', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='inventario/repuestos/', verbose_name='Foto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repuestos', to='inventario.categoriarepuesto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTR', 'Entrada'), ('SALI', 'Salida'), ('AJUS', 'Ajuste'), ('DEVO', 'Devolución')], max_length=4, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Anterior')),
                ('stock_posterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Posterior')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='ordenes.ordentrabajo', verbose_name='Orden de Trabajo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.repuesto', verbose_name='Repuesto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['codigo'], name='inventario__codigo_74f284_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['categoria', 'nombre'], name='inventario__categor_19ef61_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['stock_actual'], name='inventario__stock_a_0e11a7_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['repuesto', '-fecha'], name='inventario__repuest_08520a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo', '-fecha'], name='inventario__tipo_138e91_idx'),
        ),
    ]
