# Generated by Django 6.0 on 2026-03-05 21:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este email.'}, max_length=254, unique=True, verbose_name='correo electrónico')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('MECANICO', 'Mecánico'), ('RECEPCIONISTA', 'Recepcionista')], default='RECEPCIONISTA', help_text='Rol del usuario en el sistema', max_length=20)),
                ('telefono', models.CharField(blank=True, help_text='Formato: +34600000000', max_length=15, validators=[django.core.validators.RegexValidator(message='El formato de teléfono debe ser: "+999999999". Hasta 15 dígitos permitidos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='teléfono')),
                ('foto_perfil', models.ImageField(blank=True, help_text='Imagen de perfil del usuario (se redimensionará a 300x300px)', null=True, upload_to='usuarios/fotos_perfil/')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario puede acceder al sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('ultima_conexion', models.DateTimeField(blank=True, help_text='Fecha y hora de la última vez que el usuario inició sesión', null=True, verbose_name='última conexión')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_creacion'],
                'permissions': [('puede_gestionar_usuarios', 'Puede gestionar usuarios del sistema'), ('puede_ver_reportes', 'Puede ver reportes y estadísticas')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
