# Generated by Django 6.0 on 2026-03-05 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Ej: Toyota, Ford, BMW', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Ej: Corolla, Focus, Serie 3', max_length=100, verbose_name='Modelo')),
                ('anio', models.PositiveIntegerField(help_text='Año de fabricación del vehículo', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('matricula', models.CharField(help_text='Formato: 1234ABC o M-1234-AB', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de matrícula inválido. Ej: 1234ABC o M-1234-AB', regex='^[0-9]{4}[A-Z]{3}$|^[A-Z]-[0-9]{4}-[A-Z]{2}$|^[A-Z]{1,2}-[0-9]{4,5}$')], verbose_name='Matrícula')),
                ('bastidor', models.CharField(blank=True, help_text='17 caracteres - Vehicle Identification Number', max_length=17, unique=True, verbose_name='Número de Bastidor (VIN)')),
                ('color', models.CharField(blank=True, help_text='Color principal del vehículo', max_length=30, verbose_name='Color')),
                ('tipo_combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel'), ('ELECTRICO', 'Eléctrico'), ('HIBRIDO', 'Híbrido'), ('GLP', 'GLP (Gas Licuado del Petróleo)'), ('GNC', 'GNC (Gas Natural Comprimido)'), ('HIDROGENO', 'Hidrógeno')], default='GASOLINA', max_length=20, verbose_name='Tipo de Combustible')),
                ('kilometraje', models.PositiveIntegerField(default=0, help_text='Kilometraje actual del vehículo', verbose_name='Kilometraje')),
                ('foto_vehiculo', models.ImageField(blank=True, help_text='Foto del vehículo (opcional)', null=True, upload_to='vehiculos/fotos/', verbose_name='Foto del Vehículo')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre el vehículo', verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, help_text='Los vehículos inactivos no aparecen en búsquedas', verbose_name='Vehículo activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente', models.ForeignKey(help_text='Cliente propietario del vehículo', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['matricula'], name='vehiculos_v_matricu_f7081f_idx'), models.Index(fields=['cliente', '-fecha_registro'], name='vehiculos_v_cliente_504b77_idx'), models.Index(fields=['marca', 'modelo'], name='vehiculos_v_marca_38767a_idx')],
            },
        ),
    ]
